### ISSUE TITLE
KPT

### ISSUE THREAD

**Issue by motemen** [motemen/isucon5-qualifier#35]

**Comment by motemen** [comment]
# Keep
- ちゃんと手を止めた
- わりと落ち着いて分析してできた
- 手戻りなかった
- 準備した

# Problem
- 挑戦しなかった
- やればよかったのに二の足を踏んでしまったとこがある
- デプロイちょっと手間取った
- 全体見るのがおそかった

# Try
- 挑戦の割合を増やす

**Comment by tatsuru** [comment]
## K
- まあまあのスコアで予選通過できた
- nginx ログ解析それなりにスムーズにできた
- OS・ミドルウェア一通り見るの設定はスムーズだった

## P
- 準備手間取った部分があった
- 事前検証不足: systemd, unix domain socket
- ALTER SSD 思いつかなかった
- 時間余りがちだったけどあまり手を広げられなかった。クエリもう少し見られたと思う
- 1時間短かったかも

## T
- もっと事前に検証しとく
- 全体を見る時間を作る
- 最初に俯瞰する時間はフレキシブルに
- 1時間で見られるようにもっと準備しとく

**Comment by motemen** [comment]
# 技術顧問 (onishi) より
- 他人の挑戦エントリを読んで勉強しては？

**Comment by ichirin2501** [comment]
## K
- クエリとかDB周りは見ていきたい気持ち
- 可能ならプログラムも書いていく

## P
- 問題の把握力が圧倒的に足りなかった（データの性質など）
- >足あとは、同じ日に同じユーザーが付けた足あとは最新のものだけ残るように更新すれば表示するときのGROUP BYを無くすことができます。
- これ既存データの性質への理解が足りず、その考えに及ばなかった。初期データが削除できない状態に近かったので、既存データを上書きという発想がなかったということ
- シスプラとしての仕事してなかったなぁ
- 圧倒的準備不足
- お菓子食べる係とか言ってる場合じゃなかった
- 自分の中で競技云々以前だった
- 準備不足など諸々

## T
- シスプラとしての仕事もしたいぞ！
- 問題把握を素早く行うための準備を怠らない
- 自分の中で競技として成立させる

**Comment by motemen** [comment]
# 本選にむけて
